version: '3'

services:  

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./scripts/run_server.sh
    volumes:
      - .:/app 
    ports:
      - "7777:7777"